version: "3.3"
volumes:
  data:
    driver: local
  filestore:
    driver: local
services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "<ANY PASSOWORD>"
      POSTGRES_USER: root
      PSQL_USERNAME: root
      # POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/data/postgres
  national:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "<ANY PASSOWORD>"
      RUN_MODULE: national-api
      rootEmail: <ROOT EMAIL>
      systemCountryCode: "NG"
      name: "Antactic Region"
      logoBase64: "sss"
      IS_EMAIL_DISABLED: "true"
      LOCATION_SERVICE: OPENSTREET
      ASYNC_OPERATIONS_TYPE: Database
      HOST: "http://localhost:3030"
      DOMAIN_MAP: "true"
      EXPIRES_IN: "7200"
    volumes:
      - filestore:/app/backend/services/public
      - ./users.csv:/app/backend/services/users.csv
      - ./organisations.csv:/app/backend/services/organisations.csv
  stats:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - db
      - national
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "<ANY PASSOWORD>"
      RUN_PORT: 3100
      RUN_MODULE: analytics-api
      DOMAIN_MAP: "true"
  replicator:
    build:
      context: .
      dockerfile: ./backend/services/Dockerfile
    depends_on:
      - db
      - national
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "<ANY PASSOWORD>"
      # ,data-importer
      RUN_MODULE: replicator,async-operations-handler
      LOCATION_SERVICE: OPENSTREET
      SMTP_ENDPOINT: email-smtp.us-east-1.amazonaws.com
      SMTP_PASSWORD: ""
      IS_EMAIL_DISABLED: "true"
      ASYNC_OPERATIONS_TYPE: Database
      ITMO_API_KEY: ""
      ITMO_EMAIL: ""
      ITMO_PASSWORD: ""
      MRV_ENDPOINT: 'http://192.168.123.20:9000'
      REGISTRY_SYNC_ENABLE: true
      MRV_API_TOKEN: ''
  # async-operations-handler:
  #   build:
  #     context: .
  #     dockerfile: ./backend/services/Dockerfile
  #   depends_on:
  #     - db
  #     - national
  #   environment:
  #     DB_HOST: db
  #     DB_USER: root
  #     DB_PASSWORD: "<ANY PASSOWORD>"
  #     RUN_MODULE: async-operations-handler
  #     SMTP_ENDPOINT: email-smtp.us-east-1.amazonaws.com
  #     SMTP_PASSWORD: "<ANY PASSOWORD>"
  #     ASYNC_OPERATIONS_TYPE: Database
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        PORT: 3030
        REACT_APP_BACKEND: http://localhost:3000
        REACT_APP_STAT_URL: http://localhost:3100
        REACT_APP_COUNTRY_NAME: "CountryX"
        REACT_APP_COUNTRY_FLAG_URL: "https://carbon-common-dev.s3.amazonaws.com/flag.png"
        REACT_APP_COUNTRY_CODE: "NG"
        REACT_APP_MAP_TYPE: "None"
        REACT_APP_THEME_COLOR: '' #Theme color in Hex #000000
        REACT_APP_THEME_COLOR_GRADIENT: '' #Theme color in Hex #feb3b3
        REACT_APP_LOGIN_IMAGE_PNG: '' #PNG Image link or image path related to login.scss
        REACT_APP_LOGIN_IMAGE_WEBP: '' #PNG Image link or image path related to login.scss
        REACT_APP_COMPANY: '' # Log in page company name ex:COMPANY
        REACT_APP_GROUP: '' # Log in page  ex: LTD
        REACT_APP_SYSTEM_NAME: 'CARBON REGISTRY SYSTEM' # System name in tab and log in page
        REACT_APP_LOGO:  '' #Company logo
        REACT_APP_COMPANY_ENITITY: '' # In Logo high weight text
        REACT_APP_COMPANY_LIMITED: '' # In logo less weighed text
        REACT_APP_FAV_ICON: 'https://raw.githubusercontent.com/xeptagondev/carbon-registry/develop/web/public/favicon.png'        
    ports:
      - "3030:3030"
    depends_on:
      - db
      - national
